import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {requireText as text} from '../../../core/protocol/src/index.js';

export const CODEX_SKILL_INSTALLER_ID = 'trace.codex-skill-installer' as const;
export const CODEX_SKILL_INSTALLER_VERSION = '0.1.0' as const;

export interface SkillInstallPreview {skill_id: string; source_dir: string; target_dir: string; source_hash: string; existing_hash: string | null; changed: boolean; warnings: string[];}
export interface SkillInstallReceipt {protocol_id: 'trace.codex-skill-install'; protocol_version: '0.1.0'; status: 'installed' | 'rolled_back'; skill_id: string; target_dir: string; source_hash: string; previous_hash: string | null; backup_dir: string | null; installed_at: string;}

function absolute(value: string, field: string): string { const result = path.resolve(text(value, field)); if (!path.isAbsolute(result)) throw new Error(`${field} must be absolute`); return result; }
function shaFile(file: string): string { return createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }
function shaDir(root: string, options: {ignore_trace_receipt?: boolean} = {}): string { const files: string[] = []; const walk = (dir: string): void => { for (const entry of fs.readdirSync(dir, {withFileTypes: true}).sort((a, b) => a.name.localeCompare(b.name))) { const file = path.join(dir, entry.name); const relative = path.relative(root, file).replaceAll(path.sep, '/'); if (entry.isDirectory()) walk(file); else if (entry.isFile() && !(options.ignore_trace_receipt && relative === '.trace-skill-install-receipt.json')) files.push(`${relative}\0${shaFile(file)}`); } }; walk(root); return createHash('sha256').update(files.join('\n')).digest('hex'); }
function noSymlink(target: string): void { let cursor = target; while (true) { try { if (fs.lstatSync(cursor).isSymbolicLink()) throw new Error(`Symlink is not allowed: ${target}`); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; } const parent = path.dirname(cursor); if (parent === cursor) return; cursor = parent; } }
function skillId(sourceDir: string): string { const manifest = path.join(sourceDir, 'SKILL.md'); if (!fs.existsSync(manifest)) throw new Error('Skill source must contain SKILL.md'); const first = fs.readFileSync(manifest, 'utf8').split(/\r?\n/).find(line => /^name:\s*/i.test(line)); return text(first?.replace(/^name:\s*/i, '') ?? path.basename(sourceDir), 'skill_id', 240); }
function copyTree(source: string, target: string): void { fs.mkdirSync(target, {recursive: true}); for (const entry of fs.readdirSync(source, {withFileTypes: true})) { const from = path.join(source, entry.name); const to = path.join(target, entry.name); if (entry.isDirectory()) copyTree(from, to); else if (entry.isFile()) { fs.mkdirSync(path.dirname(to), {recursive: true}); fs.copyFileSync(from, to); } else throw new Error(`Unsupported skill entry: ${entry.name}`); } }
function defaultCodexHome(): string { const configured = process.env.CODEX_HOME; if (configured) return absolute(configured, 'CODEX_HOME'); const home = process.env.USERPROFILE ?? process.env.HOME; if (!home) throw new Error('CODEX_HOME or USERPROFILE/HOME is required'); return path.join(absolute(home, 'user_home'), '.codex'); }

export function resolveCodexSkillRoot(explicit?: string): string { return absolute(explicit ?? path.join(defaultCodexHome(), 'skills'), 'skill_root'); }

export class CodexSkillInstaller {
  readonly skillRoot: string;
  constructor(skillRoot?: string) { this.skillRoot = resolveCodexSkillRoot(skillRoot); }
  preview(sourceDir: string, skillName?: string): SkillInstallPreview { const source = absolute(sourceDir, 'source_dir'); noSymlink(source); if (!fs.existsSync(source) || !fs.statSync(source).isDirectory()) throw new Error('Skill source directory does not exist'); const id = text(skillName ?? skillId(source), 'skill_name', 240); const target = path.resolve(this.skillRoot, id); if (!(target === this.skillRoot || target.startsWith(`${this.skillRoot}${path.sep}`))) throw new Error('Skill target escapes skill root'); noSymlink(target); const existingHash = fs.existsSync(target) ? shaDir(target) : null; const sourceHash = shaDir(source); const warnings: string[] = []; if (existingHash !== null) warnings.push('existing user-level Skill will be preserved in the caller-provided backup root before replacement'); return {skill_id: id, source_dir: source, target_dir: target, source_hash: sourceHash, existing_hash: existingHash, changed: sourceHash !== existingHash, warnings}; }
  install(sourceDir: string, options: {skill_name?: string; backup_root: string; approval: string}): SkillInstallReceipt { const preview = this.preview(sourceDir, options.skill_name); if (text(options.approval, 'approval', 300) !== `approve:${preview.skill_id}`) throw new Error('USER_CONFIRMATION_REQUIRED: approval must equal approve:<skill_id>'); const backupRoot = absolute(options.backup_root, 'backup_root'); if (backupRoot === this.skillRoot || backupRoot.startsWith(`${this.skillRoot}${path.sep}`)) throw new Error('backup_root must be outside the user Skill discovery root'); noSymlink(backupRoot); fs.mkdirSync(backupRoot, {recursive: true}); const backup = preview.existing_hash === null ? null : path.join(backupRoot, `${preview.skill_id}-${Date.now()}`); const staging = `${preview.target_dir}.trace-staging-${process.pid}`; if (fs.existsSync(staging)) throw new Error('Skill staging path already exists'); let moved = false; try { copyTree(preview.source_dir, staging); if (backup) { fs.renameSync(preview.target_dir, backup); moved = true; } fs.mkdirSync(path.dirname(preview.target_dir), {recursive: true}); fs.renameSync(staging, preview.target_dir); } catch (error) { fs.rmSync(staging, {recursive: true, force: true}); if (moved && backup && !fs.existsSync(preview.target_dir)) fs.renameSync(backup, preview.target_dir); throw error; } const receipt: SkillInstallReceipt = {protocol_id: 'trace.codex-skill-install', protocol_version: '0.1.0', status: 'installed', skill_id: preview.skill_id, target_dir: preview.target_dir, source_hash: preview.source_hash, previous_hash: preview.existing_hash, backup_dir: backup, installed_at: new Date().toISOString()}; fs.writeFileSync(path.join(preview.target_dir, '.trace-skill-install-receipt.json'), JSON.stringify(receipt, null, 2) + '\n', {flag: 'w'}); return receipt; }
  rollback(receipt: SkillInstallReceipt): SkillInstallReceipt { if (receipt.protocol_id !== 'trace.codex-skill-install' || receipt.status !== 'installed') throw new Error('Unsupported Skill install receipt'); const target = absolute(receipt.target_dir, 'target_dir'); const backup = receipt.backup_dir === null ? null : absolute(receipt.backup_dir, 'backup_dir'); noSymlink(target); if (!backup || !fs.existsSync(backup)) throw new Error('No preserved user-level Skill backup is available'); if (!fs.existsSync(target) || shaDir(target, {ignore_trace_receipt: true}) !== receipt.source_hash) throw new Error('STALE_SKILL_ROLLBACK: the installed Skill changed after Trace installed it; preserve the current Skill and inspect the receipt before retrying'); const removed = `${target}.trace-rollback-${process.pid}`; fs.renameSync(target, removed); try { fs.renameSync(backup, target); fs.rmSync(removed, {recursive: true, force: true}); } catch (error) { if (!fs.existsSync(target) && fs.existsSync(removed)) fs.renameSync(removed, target); throw error; } return {...receipt, status: 'rolled_back', installed_at: new Date().toISOString()}; }
}
